site_name: Hyrox Team Performance Optimizer
site_description: Documentazione di Project Management
site_url: https://andreazavatta.github.io/Hyrox-Training-PM/
theme:
  name: material
  language: it
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Passa alla modalità scura
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Passa alla modalità chiara

docs_dir: docs
site_dir: site

plugins:
  - search

markdown_extensions:
  - toc:
      toc_depth: 0

nav:
  - Contesto: 0-Contesto/0-contesto.md
  - Scoping: 1-Scoping/scoping.md
  - Planning: 2-Planning/planning.md
  - Launching: 3-Launching/launching.md
  - Monitoring & Controlling: 4-Monitoring_Controlling/monitoring_and_controlling.md
  - Closing: 5-Closing/closing.md
